#############################################################################
# Makefile for building: E24116128_windows.exe
# Generated by qmake (3.1) (Qt 5.9.4)
# Project:  E24116128_windows.pro
# Template: app
# Command: /usr/bin/qmake-qt5 -o Makefile E24116128_windows.pro QT+=widgets 'QT+=core gui' 'QT+=widgets multimedia'
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -fno-keep-inline-dllexport -D_GNU_SOURCE -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -fno-keep-inline-dllexport -D_GNU_SOURCE -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I. -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtMultimedia -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -I. -I/usr/lib/qt5/mkspecs/cygwin-g++
QMAKE         = /usr/bin/qmake-qt5
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake-qt5 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake-qt5 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = E24116128_windows1.0.0
DISTDIR = /home/jenny/E24116128_windows/.tmp/E24116128_windows1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -lQt5Widgets -lQt5Multimedia -lQt5Gui -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = bullet.cpp \
		game.cpp \
		item.cpp \
		main.cpp \
		monster.cpp \
		platform.cpp \
		player.cpp \
		score.cpp moc_bullet.cpp \
		moc_item.cpp \
		moc_monster.cpp \
		moc_platform.cpp \
		moc_player.cpp
OBJECTS       = bullet.o \
		game.o \
		item.o \
		main.o \
		monster.o \
		platform.o \
		player.o \
		score.o \
		moc_bullet.o \
		moc_item.o \
		moc_monster.o \
		moc_platform.o \
		moc_player.o
DIST          = /usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/qt5/mkspecs/common/unix.conf \
		/usr/lib/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/qt5/mkspecs/qconfig.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/qt5/mkspecs/cygwin-g++/qmake.conf \
		/usr/lib/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/qt5/mkspecs/features/default_post.prf \
		/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/qt5/mkspecs/features/qt.prf \
		/usr/lib/qt5/mkspecs/features/resources.prf \
		/usr/lib/qt5/mkspecs/features/moc.prf \
		/usr/lib/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt5/mkspecs/features/uic.prf \
		/usr/lib/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/qt5/mkspecs/features/yacc.prf \
		/usr/lib/qt5/mkspecs/features/lex.prf \
		E24116128_windows.pro bullet.h \
		game.h \
		item.h \
		monster.h \
		platform.h \
		player.h \
		score.h bullet.cpp \
		game.cpp \
		item.cpp \
		main.cpp \
		monster.cpp \
		platform.cpp \
		player.cpp \
		score.cpp
QMAKE_TARGET  = E24116128_windows
DESTDIR       = 
TARGET        = E24116128_windows.exe


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: E24116128_windows.pro /usr/lib/qt5/mkspecs/cygwin-g++/qmake.conf /usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/qt5/mkspecs/common/unix.conf \
		/usr/lib/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/qt5/mkspecs/qconfig.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/qt5/mkspecs/cygwin-g++/qmake.conf \
		/usr/lib/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/qt5/mkspecs/features/default_post.prf \
		/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/qt5/mkspecs/features/qt.prf \
		/usr/lib/qt5/mkspecs/features/resources.prf \
		/usr/lib/qt5/mkspecs/features/moc.prf \
		/usr/lib/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt5/mkspecs/features/uic.prf \
		/usr/lib/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/qt5/mkspecs/features/yacc.prf \
		/usr/lib/qt5/mkspecs/features/lex.prf \
		E24116128_windows.pro
	$(QMAKE) -o Makefile E24116128_windows.pro QT+=widgets 'QT+=core gui' 'QT+=widgets multimedia'
/usr/lib/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/qt5/mkspecs/common/unix.conf:
/usr/lib/qt5/mkspecs/common/sanitize.conf:
/usr/lib/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/qt5/mkspecs/common/g++-base.conf:
/usr/lib/qt5/mkspecs/qconfig.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/qt5/mkspecs/features/qt_config.prf:
/usr/lib/qt5/mkspecs/cygwin-g++/qmake.conf:
/usr/lib/qt5/mkspecs/features/spec_post.prf:
/usr/lib/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt5/mkspecs/features/toolchain.prf:
/usr/lib/qt5/mkspecs/features/default_pre.prf:
/usr/lib/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/qt5/mkspecs/features/default_post.prf:
/usr/lib/qt5/mkspecs/features/warn_on.prf:
/usr/lib/qt5/mkspecs/features/qt.prf:
/usr/lib/qt5/mkspecs/features/resources.prf:
/usr/lib/qt5/mkspecs/features/moc.prf:
/usr/lib/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/qt5/mkspecs/features/uic.prf:
/usr/lib/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/qt5/mkspecs/features/file_copies.prf:
/usr/lib/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/qt5/mkspecs/features/exceptions.prf:
/usr/lib/qt5/mkspecs/features/yacc.prf:
/usr/lib/qt5/mkspecs/features/lex.prf:
E24116128_windows.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile E24116128_windows.pro QT+=widgets 'QT+=core gui' 'QT+=widgets multimedia'

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents bullet.h game.h item.h monster.h platform.h player.h score.h $(DISTDIR)/
	$(COPY_FILE) --parents bullet.cpp game.cpp item.cpp main.cpp monster.cpp platform.cpp player.cpp score.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/qt5/mkspecs/features/data/dummy.cpp
	g++ -fno-keep-inline-dllexport -D_GNU_SOURCE -pipe -O2 -Wall -W -dM -E -o moc_predefs.h /usr/lib/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_bullet.cpp moc_item.cpp moc_monster.cpp moc_platform.cpp moc_player.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_bullet.cpp moc_item.cpp moc_monster.cpp moc_platform.cpp moc_player.cpp
moc_bullet.cpp: Game.h \
		player.h \
		platform.h \
		game.h \
		monster.h \
		score.h \
		item.h \
		bullet.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt5/mkspecs/cygwin-g++ -I/home/jenny/E24116128_windows -I/home/jenny/E24116128_windows -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtMultimedia -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++ -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/x86_64-pc-cygwin -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/backward -I/usr/lib/gcc/x86_64-pc-cygwin/11/include -I/usr/include -I/usr/include/w32api bullet.h -o moc_bullet.cpp

moc_item.cpp: player.h \
		platform.h \
		game.h \
		monster.h \
		score.h \
		item.h \
		item.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt5/mkspecs/cygwin-g++ -I/home/jenny/E24116128_windows -I/home/jenny/E24116128_windows -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtMultimedia -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++ -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/x86_64-pc-cygwin -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/backward -I/usr/lib/gcc/x86_64-pc-cygwin/11/include -I/usr/include -I/usr/include/w32api item.h -o moc_item.cpp

moc_monster.cpp: player.h \
		platform.h \
		game.h \
		monster.h \
		score.h \
		item.h \
		monster.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt5/mkspecs/cygwin-g++ -I/home/jenny/E24116128_windows -I/home/jenny/E24116128_windows -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtMultimedia -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++ -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/x86_64-pc-cygwin -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/backward -I/usr/lib/gcc/x86_64-pc-cygwin/11/include -I/usr/include -I/usr/include/w32api monster.h -o moc_monster.cpp

moc_platform.cpp: player.h \
		platform.h \
		game.h \
		monster.h \
		score.h \
		item.h \
		platform.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt5/mkspecs/cygwin-g++ -I/home/jenny/E24116128_windows -I/home/jenny/E24116128_windows -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtMultimedia -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++ -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/x86_64-pc-cygwin -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/backward -I/usr/lib/gcc/x86_64-pc-cygwin/11/include -I/usr/include -I/usr/include/w32api platform.h -o moc_platform.cpp

moc_player.cpp: platform.h \
		player.h \
		score.h \
		item.h \
		game.h \
		monster.h \
		player.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/qt5/mkspecs/cygwin-g++ -I/home/jenny/E24116128_windows -I/home/jenny/E24116128_windows -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtMultimedia -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtCore -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++ -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/x86_64-pc-cygwin -I/usr/lib/gcc/x86_64-pc-cygwin/11/include/c++/backward -I/usr/lib/gcc/x86_64-pc-cygwin/11/include -I/usr/include -I/usr/include/w32api player.h -o moc_player.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

bullet.o: bullet.cpp Bullet.h \
		Game.h \
		player.h \
		platform.h \
		game.h \
		monster.h \
		score.h \
		item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bullet.o bullet.cpp

game.o: game.cpp Game.h \
		player.h \
		platform.h \
		game.h \
		monster.h \
		score.h \
		item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o game.o game.cpp

item.o: item.cpp item.h \
		player.h \
		platform.h \
		game.h \
		monster.h \
		score.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o item.o item.cpp

main.o: main.cpp game.h \
		player.h \
		platform.h \
		monster.h \
		score.h \
		item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

monster.o: monster.cpp monster.h \
		player.h \
		platform.h \
		game.h \
		score.h \
		item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o monster.o monster.cpp

platform.o: platform.cpp game.h \
		player.h \
		platform.h \
		monster.h \
		score.h \
		item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o platform.o platform.cpp

player.o: player.cpp Player.h \
		platform.h \
		player.h \
		score.h \
		item.h \
		game.h \
		monster.h \
		Bullet.h \
		Game.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o player.cpp

score.o: score.cpp score.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o score.o score.cpp

moc_bullet.o: moc_bullet.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bullet.o moc_bullet.cpp

moc_item.o: moc_item.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_item.o moc_item.cpp

moc_monster.o: moc_monster.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_monster.o moc_monster.cpp

moc_platform.o: moc_platform.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_platform.o moc_platform.cpp

moc_player.o: moc_player.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_player.o moc_player.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

